### PR TITLE
Rename README.md to Easzyyankee

### PR DESCRIPTION
**Pull request by Easzyyankee**
Magical world

### CODE REVIEW

**Comment by Easzyyankee** [comment]
You can write me for stronger development and with a little touch of magical moment. Easzyyankee@gmail.com 💥

**Comment by zyronon** [comment]
> You can write me for stronger development and with a little touch of magical moment. [Easzyyankee@gmail.com](mailto:Easzyyankee@gmail.com) 💥

I don't understand what you're doing.

**Comment by Easzyyankee** [comment]
I’m into of hacking hardware and software.

**Comment by Easzyyankee** [comment]
🎉

Easzy Yankee reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Pull request closed without merging**
